excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
line_length: 100
disabled_rules:
  - identifier_name
